# Generated by Django 6.0.5 on 2026-05-28 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('setor', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_maquina', models.CharField(max_length=100)),
                ('numero_patrimonio', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('setor', models.CharField(max_length=20)),
                ('colaborador', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maquina_atribuidas', to='cadastroApp.colaborador')),
            ],
        ),
        migrations.AddField(
            model_name='colaborador',
            name='maquina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaborador_responsavel', to='cadastroApp.maquina'),
        ),
    ]
